### ISSUE TITLE
ImportError: Biopython

### ISSUE THREAD

**Issue by Tianyu-007** [lasersonlab/pepsyn#16]
Hi,

I encountered a problem after installing the pepsyn and run pepsyn -h. The following script comes up:

Traceback (most recent call last):
  File "/Users/gty/opt/miniconda3/bin/pepsyn", line 33, in <module>
    sys.exit(load_entry_point('pepsyn==0.4.1+5.ga596921', 'console_scripts', 'pepsyn')())
  File "/Users/gty/opt/miniconda3/bin/pepsyn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/gty/opt/miniconda3/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/gty/opt/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/gty/opt/miniconda3/lib/python3.9/site-packages/pepsyn/cli.py", line 41, in <module>
    from pepsyn.codons import (
  File "/Users/gty/opt/miniconda3/lib/python3.9/site-packages/pepsyn/codons.py", line 21, in <module>
    from Bio.Alphabet.IUPAC import unambiguous_dna
  File "/Users/gty/opt/miniconda3/lib/python3.9/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

Could you please let me know how to fix it? Thank you!

Tianyu

**Comment by laserson** [comment]
I don't have time to fix it at this very moment, but maybe in the next couple weeks. The easiest workaround for you would be to install an older version of Biopython before they deprecated `Bio.Alphabet`.

**Comment by laserson** [comment]
Sorry, this did seem familiar, and actually I fixed this problem in the latest commit of `pepsyn` 😁 . I think you should install the latest version from github,

**Comment by Tianyu-007** [comment]
Thank you! I actually installed the latest version. Don't know why this still happened. Do you think it will work if I try an older version of Biopython?

**Comment by laserson** [comment]
I think something may be broken with your installation of pepsyn. What command did you use to install it?

You can see in the stacktrace you posted:
```
File "/Users/gty/opt/miniconda3/lib/python3.9/site-packages/pepsyn/codons.py", line 21, in
from Bio.Alphabet.IUPAC import unambiguous_dna
```
that the code you have installed tries to import something from `Bio.Alphabet`, which is no longer allowed. However, in the latest version of the pepsyn code, that line has been deleted:
https://github.com/lasersonlab/pepsyn/commit/a5969213e0a0ed5d514d7c5a730b93fcb78a5d2a#diff-f49d6b1aa970e78e21b21b1bf6d4d81c5317aaa79ca38ace6932ebb32ab0f043L21

and should now actually be

https://github.com/lasersonlab/pepsyn/blob/a5969213e0a0ed5d514d7c5a730b93fcb78a5d2a/pepsyn/codons.py#L21

So it looks like you're still running an older version of pepsyn.

**Comment by Tianyu-007** [comment]
You're right! I uninstalled all the file and installed again with the latest version and it worked! Thanks a lot for providing this great pepsyn tool!
